project:
  type: website
  render:
    - '*.qmd'
  resources:
    - 'images/*'
    - 'files/*'
    - 'BingSiteAuth.xml'
    - 'googleb721a429e0570127.html'

website:
  title: "Aditya Mahajan"
  search: false

  navbar:
    background: primary

    right:
      - text: Home
        href: index.qmd

      - text: Bio
        href: bio.qmd

      - text: Publications
        menu: 
        - text: Journal
          href: journals.qmd

        - text: Conference
          href: conferences.qmd

      - text: Talks
        href: talks.qmd

      - text: Students
        href: students.qmd

      - text: Teaching
        href: teaching.qmd

      - text: Activities
        href: activities.qmd

format:
  html:
    theme: spacelab
    toc: false
    toc-depth: 2

    include-in-header: 
      - text: |
          <script async data-id="101261731" src="//static.getclicky.com/js"></script>

    minimal: true

